### ISSUE TITLE
audioset data prepare

### ISSUE THREAD

**Issue by MaestroT** [Alibaba-MIIL/AudioClassfication#15]
In `audioset_dataset.py` line 89, `class_sample_count = self._get_stats()  # dataset has` however there is no function called "_get_stats()", and how to prepare the pt files for audioset data training?

**Comment by avi33** [comment]
Hi.
In order to prepare the audioset data you need to:
1. resample the audio files to 22.05KHz
2. map the labels to a list of integers indicating the class labels
3. remove the missing file links - (there are several links in which the videos were deleted from the web)
4. save the results in pkl file

regarding the _get_stats function - you are right it is indeed missing. This function shall return per label the number of occurrences, which later will used to balanced sampling. Sorry for missing this.
