### ISSUE TITLE
Urbansound8K dataset give an error loading data

### ISSUE THREAD

**Issue by young169** [Alibaba-MIIL/AudioClassfication#16]
RuntimeError: Only 16 and 32 bits are supported for signed PCM.

**Comment by avi33** [comment]
Hi, 
from where you've downloaded the dataset? can you post a link?

**Comment by young169** [comment]
I downloaded it from the official website: https://urbansounddataset.weebly.com/urbansound8k.html , after finishing the Download form.

**Comment by avi33** [comment]
sorry for the late response. i've used the samples from KAGGLE - https://www.kaggle.com/datasets/chrisfilo/urbansound8k
verified that they are readable using soundfile, librosa, and torchaudio
i need to fulfil some application to weebly in order to download it and i expect it will take several days. so for now the fastest solution will be to use the kaggle link
Avi
